name: weekly-summary

jobs:
  summary:
    name: Generate the summary
    runs-on: ubuntu-latest
    env:
      NEW_FILES: 5
      UPDATED_FILES: 5
    steps:
      - name: Get the new files
        uses: actions/checkout@v3
        with:
          fetch-depth: 50
          sparse-checkout: content
      - run: |
          git log --name-status --since="1 week ago" -- '*.md' '*.mdx' | grep '^A\s' | head -n ${{env.}}
